### ISSUE TITLE
Broken Links in the Readme.

### ISSUE THREAD

**Issue by baljeet** [michaelrambeau/demo-feathers-auth0-api#1]
Can you please update the links? Have they been moved somewhere else?

**Comment by michaelrambeau** [comment]
Hello @baljeet 
Sorry it seems that `feathersjs/feathers-demos` repository does not exist anymore.
I searched over other featherjs repositories but I could not find any demo using Auth0.

**Comment by baljeet** [comment]
Hi @michaelrambeau 
I am trying to implement authentication in my SPA(Angular) with feathers backend. I need to verify the token and store some meta data in postgres...
Can you guide me a bit? I am using node and feathers for first time.

**Comment by michaelrambeau** [comment]
Have you setup the Auth0 "client" (it should be a "NON INTERACTIVE" client, I think) ?
And then have you tried to clone this repo and to make it work?

* Clone the repo, `npm install`, `npm start`
* Set up your Auth0 credentials in the `.env`. file, as mentioned in the README.md
* Go to http://localhost:3030/auth/auth0
* You should be redirected to the Auth0 login form and then to the http://localhost:3030/auth/success page, where you can grab the user's token if you open the DevTools

The database used by the repo is a local database (NeoDB) but it should work with other databases.

I think you have to use the Sequelize adapter to be able to use a Postgres database 
https://docs.feathersjs.com/api/databases/sequelize.html

But I have never tried it so I cannot help you with this part.

This repo is only about the backend, but if it works, you can connect this backend application to any SPA.

**Comment by baljeet** [comment]
I have setup the auth0 client for SPA and google login works perfectly. Feathersjs has added a new authentication suite using which i configured auth0 and was able to login ( there is some issue with PEM certificates) but seems to work... So Frontend only and backend only seem to work... Let me try to make them work, will update soon...
Closing the thread.
